language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: Wa7TEr5m5pMvbw/2jP8JqcLaMoEcbY6t8VXy1T0U1pvLpAuvjQvgiwzlOkbBHxxZVm6HKwE0QF5vAsMe+5PorGlkQliui81ydwOeNhfGF6swUuZ7IbrDTbClxC/W7HsIQ23+zcXXnTP9ozE005VoqX6DaAwdO3gw/vYEgVvr5I9q4P0AldTloe0jookslsbmGtmT41QSoP0OPaxRt+k1PR8/3SayaoQPL5gebQsFwGl8tLfjY17NLraZfoWnXqehyQMovan9YHu6SfG4mHJaI7AKq6METFbRnjsuI9AMj6IoYJZI9s7M5IecDNxvTQVeWBR/+ip/TgyGbHKAW4idud7kurHngRn9MpYpX7JLaFMPYMcqILGXdC9qLWlLW86uJBsxVx5tMQ2XZsmGMoF1NO2w4dhZb7XJnrgRHPcvpYfL1Ilx8OK4tn51L/r7jzeqE3KSmYfFBAIEYZXuLHqu18AX/XeOKvxqZiwhvIYGXLTk0ZeE9WfzWJw6h4q0Y8C6lhEbMDP7hDwyhZRsi7rSzOoR6WdoRRvih1B0VxbwJqPzB5hB760sLGL4riLaAOciXFg5DC6a/Sy5nOxWAZuxYVn8ZUiFCgKn+aAfmZt3rUknRvq49B3bb6T3f0k8dtqcoeMs5MTrab7V3k0FLhhqUIfX8k6jM37oPOUvbHPGu5Q=
  - secure: Y/TWVeXjWvnb584E7kZ46tW+TSCnf3N1bBK7strPd40oieAi+GYiWVl2Z8vbHOp9sQNwXyvuK5ExrBqmr1ziJgzW6SKqUQ0A2S6KWRnWVA2JwrLaoEi+7rolilQxEKmyq35pIesu4fL3Y7ra+zjLCcavQOHe8xu8Xljiwx2FlSvye6vDF+9DVzLYhPVU/AKS0AiNvqbqPcXtlGoysM8aN+P87nrNhnT/BZVlKysk/DjwUQ410s+th0wiRaFylDR3vrssQdk6Kuy5oNqPhhEIYlJvQXduaLcP6qyCyGfn8M3eWoa8N45rFOW59IICtQRGG/BEuyd+3b87nLv88U3ANumKvIO2u/brZ7OfxtABdFRVVbs3IdWGpDl6uHrmNwWb5uUBI2se8pFT7FqR81rKRcIJkhUQWWoXAg/WHhojrNFpQ8xm9wY3oCmk9XyMgGJ/ZQRxDyZIir1wjhnIqqTmbr36OtC6Bg1PkBhSLwkbHgUF5n4fP8LNeGQU0B2zAjuT6fx5ylUHJ9R6+DWC+NvZEqGkdzabUiwHvttC7ggPiOfAkubretY+2MZ7svMQpr51k7SiopofviU3EDeOBIPdCtCbrcKRm64ndTYZpUNpNmtNcp9u2uX6HWnnQyc2rJl/xUTmlHm28K7Qerxry/9YDe/UkUXqAiYTV6cvXDI5Afg=
